#!/usr/bin/env python3
"""Build the fixed 28-story legacy backlog. Run only when maintaining the package."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "content/backlog"

SEEDS = [
 ("The Thirteenth Floor","My building has twelve floors, but last night the lift stopped at thirteen.","The corridor copied my home, including photographs of me living with strangers. An older version of me pressed a bloodstained key into my hand and warned me about her husband. When I escaped downstairs, my husband said his key no longer worked. The bloodstained key opened our flat, where every family photograph now showed him beside the older woman.","In every picture, I was outside the window, watching them."),
 ("My Future Voicemail","At midnight, I received a voicemail from myself—recorded tomorrow.","My future voice warned me not to admit Marcus, the brother I had left to drown years earlier. He appeared outside without having aged, while another voicemail screamed that I had already opened the door. When the doorstep camera showed nobody there, I finally remembered Marcus had never returned from the lake.","Someone locked the door behind me, and wet footprints led from the hallway to the phone in my hand."),
 ("The Empty Cot","The baby monitor started crying three months before my baby was born.","Although I unplugged it, the screen showed our empty nursery one year in the future. Future me silently told me to check the attic. There I found old baby clothes, hospital records and a death certificate for an infant son bearing my name. My husband called from downstairs and said I was never supposed to remember him.","Then the attic door locked, and the unplugged monitor began playing a lullaby beside me."),
 ("Return to Sender","A parcel arrived containing everything I would need to murder my husband.","A note ordered me to act before nine, and a photograph proved someone had entered our bedroom. At dinner my husband reached beneath the table, so I raised the parcel's knife. He produced a wedding ring, waited until I lowered the blade, then opened a drawer filled with identical notes, photographs and rings addressed to other women.","Our wedding picture showed six different women wearing my face, and he whispered, 'Time to try again.'"),
 ("The Steps I Didn't Take","My fitness watch recorded 3,842 steps while I was asleep.","Its route ended in the abandoned house next door, where I found photographs of sleeping strangers and tomorrow's date behind my neighbour's picture. Police found only my fingerprints and my watch charger. That evening, my neighbour vanished. I locked myself inside, but the watch congratulated me for completing another walk.","Then a woman screamed beneath my bedroom floor, and the step counter increased by one."),
 ("The School Pickup Code","A stranger collected my daughter using our private school pickup code.","Her tablet showed that she had sent him photographs of our alarms and a message saying I still did not remember him. My husband called from abroad and insisted we had no daughter. Her bedroom emptied around me until only her yellow coat remained. Inside its pocket was that day's class photograph.","Every child smiled at the camera while I stood behind them dressed as their teacher."),
 ("The Funeral Livestream","During my sister's funeral livestream, the woman inside the coffin opened her eyes.","Lucy messaged me to stop watching, so I drove to her house and found her tied to a chair. Once freed, she whispered that I should never have returned. Her husband showed me the stream's timestamp: tomorrow. The camera moved close enough to reveal that the body in the coffin was mine.","Lucy locked the front door and calmly said, 'Now we can film the beginning.'"),
 ("The Extra Room","My hotel room had a door that was missing from the floor plan.","Behind it I found luggage, phones and photographs showing me watching previous guests sleep. Security footage showed I had checked in with a frightened woman I could not remember. Reception called to say my wife was waiting downstairs, although I was unmarried. Someone knocked at the main door.","From the hidden room, another woman whispered, 'Don't believe her. I made that mistake last time.'"),
 ("The Babysitter's Rule","The family gave me one rule: never open the basement door.","Their son asked why I was pretending to be his babysitter, then gave me the basement key. Below, videos showed me explaining that he was my son and my husband repeatedly erased my memory. Headlights arrived. The father entered with a medical bag, saw what I had discovered and filled a syringe.","He promised that tomorrow I would become the new babysitter—and this time I would receive no key."),
 ("The Final Passenger","The last passenger on my night bus refused to get off.","At the terminal, every seat filled with people from roadside memorials along my route. A newspaper reported that seventeen passengers had died when their driver fell asleep, and my photograph appeared under the headline. I drove the route again, letting each ghost disappear where they had died.","My stop never came because only seventeen bodies were recovered; the missing driver's body was mine."),
 ("The Returned Wedding Dress","A dry cleaner returned my wedding dress covered in fresh blood.","The receipt said my missing husband had delivered it yesterday. Police arrived after finding his blood in my car, but the gown vanished from beneath my bed. I found him alive inside the wardrobe. He thanked me for letting detectives see me hide it, then escaped through a concealed door and tossed me his phone.","His final message to the lead detective promised they could be together once I was convicted."),
 ("The Sleep Recording","My sleep app recorded me confessing to a murder I couldn't remember.","The recording said I buried my therapist beneath his greenhouse. He appeared there alive and admitted planting confessions in my sleeping mind so I would depend on him. I secretly recorded his admission, but he smiled and asked whether I still believed I was holding my own phone. Its screen changed to a bedroom camera.","I was still asleep there, hearing my own voice command me to wake up and kill him."),
 ("The Smart Speaker","My smart speaker played a recording of my husband planning my murder.","When I confronted him, it played my voice helping with the plan. Neither of us remembered speaking. A third voice—our counsellor—ordered us to repeat the scheme until we believed it. We discovered four of his former couples had died in apparent murder-suicides, and our medicine labels had been switched.","The speaker declared the session complete as my husband received an order to begin the final exercise and locked the kitchen."),
 ("The Library Book","The final page of my library book described exactly how I would die.","The untitled novel documented my entire life, then predicted the librarian locking every exit at 6:14. I resisted its instruction to hide under a desk until something dragged itself between the shelves. Beneath the desk my hand touched cold fingers under the carpet. The librarian approached carrying a blank volume.","She said readers always obey the ending, and my returned book grew a cover bearing my face and tomorrow's due date."),
 ("The Dental X-Ray","My dentist found a tracking device inside my jaw.","The capsule matched X-rays from six patients who disappeared after visiting our childhood clinic. When its light blinked, two men entered and dragged the dentist away while I hid in a cupboard. A caller thanked me for locating their defective tracker, lost twenty years earlier. The cupboard light switched on.","Its walls were covered with childhood photographs of me sleeping—and the dentist had taken every one."),
 ("The Missing Minute","My dashcam deletes the same minute from every journey.","A hidden second camera showed me collecting an escaped woman in a hospital gown and driving her to a warehouse. An officer deleted the evidence and claimed I transported dangerous patients for a secret programme. Then the camera revealed an identical hospital wristband beneath his sleeve. The dashboard returned to 11:46 as he raised a syringe.","When I woke, the woman was gone and exactly one minute had vanished again."),
 ("The Emergency Alert","At 2:06 a.m., my phone warned me not to look outside.","A supposed officer knocked while alerts called him an escaped prisoner. Masked people entered houses evacuated by an earlier false warning. The officer forced my door; beneath his mask was my husband. Police found the neighbours' valuables in his van and arrested him. His phone received one final instruction asking why he had not finished the job.","The sender was saved as Wife, but the number was not mine."),
 ("Borrowed Coat","The second-hand coat had a warning stitched inside: if he follows you, pretend your name is Anna.","A man followed me and showed photographs of the previous owner outside my home. Police detained him, but a second note thanked me for giving him someone new. Twelve women wearing the same coat were listed as missing. That night, a woman unlocked my flat, collected the coat and photographed me.","She had never been escaping the stalker; she was choosing his next victims."),
 ("The Thirteenth Bell","Our village church rang thirteen times whenever someone was about to disappear.","A boy from a forty-year-old missing poster hid me in the tower while villagers, including my father, climbed after us. They claimed one yearly sacrifice protected every child. The boy told me to cut the rope. The bell crashed through the floor, revealing hundreds of bones beneath it.","There was no curse or monster—only generations of murders hidden by the entire village."),
 ("Lost Property","A suitcase containing my clothes arrived at airport lost property before I lost it.","It held bloodstained clothes, cash and tomorrow's boarding pass. A recorder exposed my manager's smuggling and his plan to frame me, so police arrested him. When officers reopened the case, the money had vanished. My colleague thanked me for removing him and displayed tomorrow's boarding pass.","It carried my name but her photograph; I had helped her steal the operation."),
 ("The Museum Guide","The museum audio guide described my murder before it happened.","It directed me away from a running guard and into an empty display case. The guard instead told me to check my handbag, where I found a stolen pendant. My boyfriend had planted it and programmed the guide to move me away from security while he escaped. Police caught him waiting in our car.","The guide announced that I survived but he did not, seconds before the car exploded."),
 ("The Tide Marks","Every morning, wet footprints appeared beside my bed.","A dripping boy led me to names and rising lines hidden beneath the wallpaper. They recorded floods, and the highest mark bore tomorrow's date. An engineer discovered the cottage blocked an old storm channel while my landlord had concealed every warning. We evacuated before the tide destroyed the building.","Rescuers found the boy's skeleton below the floor; his ghost had been warning us about the water that killed him."),
 ("The Empty Ambulance","An ambulance arrived for me before I called for help.","Its dashboard counted down as an allergic reaction tightened my chest. Inside, an injection carried my name, and the doors locked. My business partner followed with a remote controller after increasing my life insurance. Police stopped him when I escaped. Doctors examined the labelled medicine.","It contained the allergen; the countdown measured how long he expected me to resist taking it."),
 ("The Final Broadcast","The radio presenter announced my disappearance while I was still driving home.","A woman hiding in my boot claimed she was the real presenter and that an obsessed technician predicted crimes before committing them. At the station police arrested him using prerecorded voice samples. Then the woman entered the booth, locked the door and resumed the broadcast in her own voice.","The technician had not stolen her programme; she had hired him to create the perfect alibi."),
 ("The Photo Booth","The photo booth printed a picture of someone standing behind me.","Successive photographs showed a glove, a syringe and my unconscious body inside a van. Police discovered a hidden camera transmitting to a kidnapper outside. My strip contained a message saying its final picture had been changed. The remote account belonged to the first woman he abducted.","He had forced her to select new victims, but she had altered my photograph to help me escape."),
 ("The Locked Greenhouse","My neighbour's greenhouse light switched on whenever someone disappeared.","Inside, jewellery from missing people hung from enormous flowers. Police found no bodies, only ordinary fertiliser and deliberate evidence, but human fragments clung to my shoes. I realised the soil came from my own garden. At home, my husband emptied another bag beneath our roses and watched officers search next door.","He smiled and said the greenhouse had worked: everyone was digging in the wrong garden."),
 ("The Borrowed Shadow","My shadow entered the house five seconds before I did.","It pointed me toward hidden speakers and cameras while footsteps moved upstairs. Police found my landlord in the attic with recordings and copied keys; he claimed he projected the shadow to frighten me away. But his projector faced the wrong wall. Security footage showed a dark shape rising behind him.","My shadow had not entered to scare me—it had gone inside to lock him in."),
 ("The Last Ferry","The ferry ticket listed one more passenger than the boat carried.","The captain dismissed the extra name, Samuel Reed, before the engines failed and water entered below. Insurance papers exposed his plan to sink the vessel. Then Samuel climbed aboard, soaked, saying the captain had pushed him overboard before departure. He had listed himself to prove he boarded and transmitted the evidence.","His inspection report was fake: he came because his brother died on the captain's previous ferry."),
]

FILLER = [
 "For several seconds I could hear nothing except my breathing and the small ordinary sounds around me.",
 "Every explanation I tried made the details worse, because each clue had been placed where I alone would find it.",
 "I wanted to leave immediately, but doing that would mean abandoning the only proof that any of this had happened.",
 "The silence felt deliberate, as though someone nearby was waiting for me to understand the trap before moving again.",
]

TAGS = ["#HorrorTok","#ShortHorror","#CreepyStories","#PsychologicalThriller","#SuspenseStory","#PlotTwist","#FacelessStories","#ShortFormVideo","#TikTokStories"]

def count(text): return len(re.findall(r"\b[\w’'-]+\b", text))

def narration(seed, index):
    title, hook, middle, ending = seed
    parts = [hook, middle]
    cursor = index
    while count(" ".join(parts + [ending])) < 130:
        sentence = FILLER[cursor % len(FILLER)]
        if count(" ".join(parts + [sentence, ending])) <= 155:
            parts.append(sentence)
        else:
            needed = 130 - count(" ".join(parts + [ending]))
            parts.append(" ".join(sentence.split()[:needed]))
        cursor += 1
    return " ".join(parts + [ending])

def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for index, seed in enumerate(SEEDS, 1):
        title = seed[0]
        slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
        story = {
            "id": f"backlog-{index:02d}-{slug}", "title": title,
            "narration": narration(seed, index),
            "description": f"{title}. An original one-minute horror story. {' '.join(TAGS + ['#' + re.sub(r'[^A-Za-z0-9]', '', title)])}",
            "voice": "en-GB-SoniaNeural", "speech_rate": "+14%", "speech_volume": "-14%", "speech_pitch": "-8Hz",
            "background": "", "music": ""
        }
        (OUT / f"{index:02d}-{slug}.json").write_text(json.dumps(story, indent=2, ensure_ascii=False)+"\n", encoding="utf-8")

if __name__ == "__main__": main()
